"""empty message

Revision ID: 0ef489c9bd2f
Revises: 
Create Date: 2023-04-12 12:30:09.048955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef489c9bd2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lyrics', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_songs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mp3', sa.String(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_files_song_id_songs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagged_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songs_key', sa.Integer(), nullable=False),
    sa.Column('tag_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['songs_key'], ['songs.id'], name=op.f('fk_tagged_songs_songs_key_songs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_key'], ['tags.id'], name=op.f('fk_tagged_songs_tag_key_tags')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagged_songs')
    op.drop_table('files')
    op.drop_table('songs')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
